name: build
'on':
  push:
    branches:
      - main
jobs:
  net-framework:
    runs-on: windows-latest
    steps:
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
      - name: Restore nuget packages
        run: nuget restore DicomScoToBto.sln
      - name: Build
        run: >-
          msbuild DicomScoToBto.sln -p:Configuration=Release -p:UseSharedCompilation=false
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2
